### PR TITLE
Review

### PR DESCRIPTION
**Pull request by lasote**
- fPIC removed when windows
- packaged license

### CODE REVIEW

**Comment by lasote** [comment]
Ouch, CI failing hard. I'll take a look.

**Comment by solvingj** [comment]
I don't understand what you mean by "local method not allowed yet". Can you explain?
`cmake.configure()` is not supposed to be rooted in `self.source_subfolder`, it's supposed to be rooted in the source folder, which is where the wrapper `CMakeLists.txt` should be.  We don't target the projects `CMakeLists.txt` file directly.

**Comment by lasote** [comment]
Forget it. I thought that there was something bad. But I was wrong. The pure local flow is not supported because of the `exports_sources` not copied automatically to the source. There is already an issue and a pet implementation to achieve it.

**Comment by solvingj** [comment]
Oh, wow, great to know!

**Review by SSE4 — APPROVED** [review]
LGTM

**Pull request merged**
